server:
  port: 8082
  servlet:
    context-path: /post/api/v1

spring:
  application:
    name: post-service
  datasource:
    url: jdbc:mysql://localhost:3306/post_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  signerKey: ${JWT_SIGNER_KEY:1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij}

app:
  security:
    public-post-endpoints:
      - "/posts/public"
