server:
  port: 8084
  servlet:
    context-path: /chat/api/v1

spring:
  application:
    name: chat-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/chat_db
      auto-index-creation: true

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: chat-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

jwt:
  signerKey: ${JWT_SIGNER_KEY:1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij}

app:
  services:
    identity-service:
      url: http://localhost:8081/identity/api/v1
  security:
    internal-api-key: ${INTERNAL_API_KEY:12345678trideptrai}